### ISSUE TITLE
[BUG] AJAX error when attempting to connect Blocto wallet to RPS app

### ISSUE THREAD

**Issue by sisyphusSmiling** [onflow/walletless-arcade-example#94]
### Current Behavior

Currently, requests to Blocto are not successful when connecting Blocto wallet to the RPS game. Currently hangs after entering Blocto credentials to login and connect my wallet.

Update: Looks like there's a 401 response on a GET request to https://flow-wallet-dev.blocto.app/blocto/account/assets? with response of `{"error_code":"auth_fail","message":"invalid token"}`

### Expected Behavior

When a user elects to connect their Blocto wallet to the RPS game, the request should be successful and they should be presented with a multi-sign transaction that adds the app account as a child to their wallet-managed account.

### Steps To Reproduce

Run the RPS client locally against Testnet and proceed through gameplay until you win a game. Then hit "settings' and connect your account.

### Environment

```markdown
- OS: macOS 13.4.1 (c)
- Node: 16.6.0
- npm: 9.8.0
```

**Comment by sisyphusSmiling** [comment]
cc: @JeffreyDoyle @gregsantos I know you're both working on other things atm, but wondering if you all might know offhand why this error is coming up. I couldn't find anything in the Blocto docs

**Comment by bthaile** [comment]
Interesting, I was able to connect my blocto wallet. 
but when browser is incognito, I get the "AjaxError" error. 

![image](https://github.com/onflow/walletless-arcade-example/assets/3970376/13df77d1-7e90-409e-9b88-cede93a29f05)

**Comment by sisyphusSmiling** [comment]
Yeah, that's totally what's going on. That's what I get for trying to debug frontend 😅 Thanks for clearing that up, I'll close the issue now.

**Comment by bthaile** [comment]
I was able to login to flow port incognito, so I'm a bit confused. I can see if what differences there are with login.
